### ISSUE TITLE
env ??

### ISSUE THREAD

**Issue by smurfix** [cloudnull/systemd-netns#2]
systemd.service:
```
           For each of the specified commands, the first argument must be either an absolute path to
           an executable or a simple file name without any slashes. …
```
In other words, systemd already does path lookup. Thus all those /usr/bin/env calls in your service files have absolutely no effect, other than slightly slowing down starting the services.

**Comment by cloudnull** [comment]
Thanks for the note. The repos was created to show how something could be done and not something that I actually use. So I'm not going to update anything in tree but I appreciate you letting me know. TIL.
